### ISSUE TITLE
Doesn't seem to work with current version of Create React App / how to embed site

### ISSUE THREAD

**Issue by openSourcerer9000** [tribeplatform/react-sdk-tutorial#1]
I believe Facebook just broke the internet, presumably to stifle rival social networks like tribe...

Something to do with "webpack no longer supports node.js packages, polyfills etc etc", I've had this problem in other react projects, and attempting to downgrade to previous packages just breaks this 3000 package dependency hell beyond repair.

I'm trying to simply embed some featured content from my Tribe community into a react site using CRA 5.0.0. I'm trying to follow this instruction, I just `npm install @tribeplatform/react-sdk`ed and then pasted the snippet provided directly into my app.js to attempt to print the access token, changing the fields inside curvy brackets. For {memberId}, I just put my user name from the community, that part wasn't documented so that was my best guess.

[https://partners.tribe.so/docs/guide/javascript-client/generating-access-token/](https://partners.tribe.so/docs/guide/javascript-client/generating-access-token/)
```
import { TribeClient } from "@tribeplatform/gql-client"

const client = new TribeClient({
    clientId: "{clientId}",
    clientSecret: "{clientSecret}",
    graphqlUrl: "https://app.tribe.so/graphql",
})

client.generateToken({
    networkId: "{networkId}",
    memberId: "{memberId}",
}).then(async accessToken => {
    console.log(accessToken)
})
```

Which results in this error:
```
graphql.client.ts:90 Uncaught (in promise) ReferenceError: Buffer is not defined
    at GraphqlClient.getBasicToken (graphql.client.ts:90:1)
    at GraphqlClient.authorizedRequest (graphql.client.ts:103:1)
    at TribeClient.getLimitedToken (client.ts:154:1)
    at TribeClient.generateToken (client.ts:181:1)
    at Module../src/App.js (App.js:15:1)
    at Module.options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:61:1)
    at Module../src/index.js (GlobalStyles.js:99:1)
    at Module.options.factory (react refresh:6:1)
```

`npm install buffer` doesn't help, and attempting to revert CRA or webpack versions breaks everything. 

If I eventually can find my access token, is this embed feature even available at the basic tier? It doesn't seem to specify, thanks.

**Comment by keyvankhademi** [comment]
The code you shared it for generating token when writing an "App" in Tribe. From what I understand you don't want to create an App but you only want to embed some features.
You can use this code which is mentioned below your code in the link you shared.
```
import { TribeClient } from "@tribeplatform/gql-client"

const client = new TribeClient({
  graphqlUrl: "https://app.tribe.so/graphql",
})

const getAccessToken = async (usernameOrEmail, password) => {
  const guestTokens = await client.getTokens(
    { networkDomain: "{yourcommunityaddress.tribe.so}" },
    "basic"
  )
  client.setToken(guestTokens.accessToken)

  const { accessToken, refreshToken } = await client.auth.login(
    {
      input: { usernameOrEmail, password },
    },
    "basic"
  )

  console.log({ accessToken, refreshToken })
}

getAccessToken("{usernameOrEmail}", "{password}")
```
